# This is a Deployment config and it is used to define
# containers (their images, ports and resources) that will
# be deployed to the a pod in the k8 cluster. The metadata
# name is used to reference the deployment in other k8s
# config files. The labels are used to select the deployment
# in other k8s config files.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app-client # <- name of the deployment (must be unique in the namespace)
  labels:
    app: example-app
    component: client

spec:
  replicas: 1 # how many pods need to be running at all times
  selector:
    matchLabels:
      component: client
  template:
    metadata:
      labels:
        component: client
    spec:
      containers:
        - name: client
          image: thisoliver/example-kubernates-app:client # <- tag is important
          imagePullPolicy: Always
          #image: example-kubernates-app:client # <- local image
          #imagePullPolicy: Never # <- forces k8 controller to use local image
          env:
            - name: NUXT_PUBLIC_API_BASE
              value: "http://example-app-server:4000" # <- service name for server deployment (see service-server.yaml)
          ports:
            - containerPort: 3000
              name: client-port
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
