apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app-client
  labels:
    app: client

spec:
  replicas: 3
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      #imagePullSecrets:
      #  - name: example-app-docker-credentials # <- required to pull images in private registry/repository (value from name in secret.yaml)
      containers:
        - name: client
          image: thisoliver/example-kubernates-app:client # <- tag is important
          #image: example-kubernates-app:client # <- local image
          #imagePullPolicy: Never # <- forces k8 controller to use local image
          env:
            - name: NUXT_PUBLIC_API_BASE
              value: http://example-app-server:4000 # <- use name of server deployment
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
