apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app-server
  labels:
    app: server

spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: thisoliver/example-kubernates-app:server # <- tag is important
          #image: example-kubernates-app:server # <- local image
          #imagePullPolicy: Never # <- forces k8 controller to use local image
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: example-app-secrets # <- value from metadata.name in secrets.yaml
                  key: jwt-secret
          ports:
            - containerPort: 4000
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
