apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: example-app

resources:
  - secrets.yaml
  - deployment-server.yaml
  - deployment-client.yaml
  - service-server.yaml
  - service-client.yaml
