apiVersion: v1
kind: Service
metadata:
  namespace: example-app-space
  name: example-app-service-client
  labels:
    app: client

spec:
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 3000
