# See service-client.yaml for a brief explanation of the service config.

apiVersion: v1
kind: Service
metadata:
  name: example-app-server
  labels:
    app: example-app
    component: server

spec:
  type: ClusterIP
  selector:
    component: server # <- selects the deployment with the label app: example-app
  ports:
    - protocol: TCP
      targetPort: server-port # <- client container in deployment.yaml
      port: 4000 # <- port for external access
