name: Deploy Images

on:
  push:
    branches:
      - main

env:
  image: thisoliver/example-kubernates-app

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # get code
      - name: Checkout
        uses: actions/checkout@v4
      
      # setup quemu to build for multiple architectures
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # idk
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # login to docker hub (use token instead of password)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # build and push server image
      - name: Deploy Server
        uses: docker/build-push-action@v2
        with:
          # run docker build in packages/server
          context: packages/server
          tags: ${{ env.image }}:server
          push: true



  